# Generated by Django 3.1.1 on 2020-11-03 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, verbose_name='Descripcion')),
                ('ip', models.CharField(default='192.168.0.254', max_length=20)),
                ('topic', models.CharField(default='device1/#', max_length=300, unique=True)),
                ('puerto', models.IntegerField(default=9001)),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=200)),
                ('tfno', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('password', models.CharField(max_length=15, verbose_name='Contraseña')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('tiempo_produccion', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('horario1', models.CharField(default='8:00', max_length=8)),
                ('horario2', models.CharField(default='17:00', max_length=8)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_riego.device')),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_riego.persona')),
            ],
            options={
                'verbose_name': 'Plataforma',
                'verbose_name_plural': 'Plataformas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoRol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'TipoRol',
                'verbose_name_plural': 'TipoRoles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoSensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'TipoSensor',
                'verbose_name_plural': 'TipoSensores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoSuelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('densidad', models.DecimalField(decimal_places=2, max_digits=1000)),
            ],
            options={
                'verbose_name': 'TipoSuelo',
                'verbose_name_plural': 'TipoSuelos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Siembra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_siembra', models.DateTimeField()),
                ('cantidad_plantas', models.IntegerField()),
                ('distancia_siembra', models.DecimalField(decimal_places=2, max_digits=3)),
                ('planta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_riego.planta')),
                ('plataforma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_riego.plataforma')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('codigo_sensor', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=1)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_riego.device')),
                ('tipo_sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_riego.tiposensor')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='plataforma',
            name='tipo_suelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_riego.tiposuelo'),
        ),
        migrations.CreateModel(
            name='HistorialRiego',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tiempo_riego', models.DecimalField(decimal_places=2, max_digits=3)),
                ('fecha_riego', models.DateTimeField(auto_now_add=True)),
                ('siembra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_riego.siembra')),
                ('tipo_rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_riego.tiporol')),
            ],
            options={
                'verbose_name': 'HistorialRiego',
                'verbose_name_plural': 'HistorialRiegos',
                'ordering': ['-id'],
            },
        ),
    ]
