# Generated by Django 3.1.1 on 2020-09-22 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_riego', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='tipo_sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TipoSensor', to='gestion_riego.tiposensor'),
        ),
    ]
