# Generated by Django 3.1.1 on 2020-09-22 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_riego', '0002_sensor_tipo_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_riego.device'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='tipo_sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_riego.tiposensor'),
        ),
    ]
