# Generated by Django 3.1.1 on 2020-09-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_riego', '0002_auto_20200920_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temp_ambiente', models.IntegerField()),
                ('humed_ambiente', models.IntegerField()),
                ('humed_suelo', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
