# Generated by Django 3.1.1 on 2021-01-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_riego', '0002_auto_20210116_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialriego',
            name='image_1_variable',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='historialriego',
            name='image_3_variable',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='historialriego',
            name='image_4_variable',
            field=models.BinaryField(null=True),
        ),
    ]
