# Generated by Django 3.1.1 on 2020-09-23 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_riego', '0003_auto_20200922_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSuelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('densidad', models.DecimalField(decimal_places=2, max_digits=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='tiposensor',
            name='descripcion',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('planta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_riego.planta')),
                ('tipo_suelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_riego.tiposuelo')),
            ],
        ),
    ]
