# Generated by Django 3.1.1 on 2020-09-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_riego', '0003_auto_20200920_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='humed_ambiente',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='humed_suelo',
            field=models.DecimalField(decimal_places=2, max_digits=1023),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='temp_ambiente',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
