# Generated by Django 3.1.1 on 2020-09-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_riego', '0004_auto_20200920_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='sensor',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
