# Generated by Django 3.1.1 on 2020-09-24 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_riego', '0004_auto_20200922_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='plataforma',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_riego.device'),
        ),
    ]
