# Generated by Django 3.1.1 on 2021-01-18 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_riego', '0005_auto_20210117_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialriego',
            name='tiempo_riego',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='historialriego',
            name='tiempo_riego_1_variable',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='historialriego',
            name='tiempo_riego_4_variable',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
