# Generated by Django 3.1.1 on 2020-10-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_riego', '0005_plataforma_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='puerto',
            field=models.IntegerField(default=9001),
        ),
        migrations.AddField(
            model_name='device',
            name='topic',
            field=models.CharField(default='device1/#', max_length=300),
        ),
    ]
