# Generated by Django 3.1.1 on 2020-10-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_riego', '0006_auto_20201012_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ip',
            field=models.CharField(default='192.168.0.6', max_length=20),
        ),
    ]
