# Generated by Django 3.1.1 on 2020-10-13 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_riego', '0007_device_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialRiego',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=100)),
                ('tiempo_riego', models.IntegerField()),
                ('fecha_riego', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_riego.device')),
            ],
        ),
    ]
