# Generated by Django 3.1.1 on 2020-10-13 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_riego', '0008_historialriego'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRol',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='historialriego',
            name='rol',
        ),
        migrations.AlterField(
            model_name='historialriego',
            name='tiempo_riego',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AddField(
            model_name='historialriego',
            name='tipo_rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_riego.tiporol'),
        ),
    ]
