# Generated by Django 3.1.1 on 2020-10-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_riego', '0009_auto_20201013_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialriego',
            options={'ordering': ['-id']},
        ),
    ]
