# Generated by Django 3.1.1 on 2020-10-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_riego', '0011_auto_20201018_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='plataforma',
            name='horario1',
            field=models.CharField(default='8:00', max_length=8),
        ),
        migrations.AddField(
            model_name='plataforma',
            name='horario2',
            field=models.CharField(default='12:00', max_length=8),
        ),
        migrations.AddField(
            model_name='plataforma',
            name='horario3',
            field=models.CharField(default='17:00', max_length=8),
        ),
    ]
