# Generated by Django 3.1.1 on 2020-10-25 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_riego', '0012_auto_20201021_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siembra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_siembra', models.DateTimeField(auto_now_add=True)),
                ('cantidad_plantas', models.IntegerField()),
                ('distancia_siembra', models.DecimalField(decimal_places=2, max_digits=3)),
                ('tamanio_parcela', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='historialriego',
            name='device',
        ),
        migrations.AddField(
            model_name='planta',
            name='tiempo_produccion',
            field=models.IntegerField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip',
            field=models.CharField(default='192.168.0.254', max_length=20),
        ),
        migrations.AddField(
            model_name='historialriego',
            name='siembra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_riego.siembra'),
        ),
    ]
