# Generated by Django 3.1.1 on 2020-10-25 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_riego', '0013_auto_20201025_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='tiempo_produccion',
            field=models.IntegerField(null=True),
        ),
    ]
