# Generated by Django 3.1.1 on 2020-10-25 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_riego', '0014_auto_20201025_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='siembra',
            name='planta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_riego.planta'),
        ),
        migrations.AddField(
            model_name='siembra',
            name='plataforma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_riego.plataforma'),
        ),
    ]
